Restructuring for akka application
funfunStudy/funfunnet-crawler pull request #3
Opened 2017-08-23 12:34 UTC by insford

Akka application으로 리스트럭처링 + 아카 스케쥴러 구현

- 기반 akka-quickstart : http://developer.lightbend.com/guides/akka-quickstart-scala/running-the-application.html
- akka scheduler : http://doc.akka.io/docs/akka/2.5.3/scala/scheduler.html
- akka quartz-scheduler : https://github.com/enragedginger/akka-quartz-scheduler

위 3가지를 참고하여 기본기능 구현했습니다.
quickstart sample code는 참고차.. 일단 남겨놨어요. 다음 커밋때 삭제하면 될 것 같습니다.

2017-08-23 12:40 UTC, insford commented
이슈 컨넥트하는게 어디 있었던것 같은데... 참고 - funfunStudy/funfunnet#32

2017-08-23 15:47 UTC, goinhacker commented
branch명 생성하실때, feature/[이슈번호]-[브랜치명] 요렇게 생성해주세요. 
예를들면, 이번 브랜치 같은경우는 feature/32-crawler-batch 정도가 되겠네요. 
프로젝트 이슈관리는 전부 funfunnet repo에서 하고 있어서 불편한 감이 있긴하지만... 초반에 그렇게 하기로 일단 결정했으니 ..

2017-08-23 16:03 UTC, goinhacker requested changes

2017-08-23 16:03 UTC, goinhacker commented on README.md
> +java -jar target/scala-2.12/funfunnet-crawler-assembly.jar
빌드하면 생기는 gradle wrapper도 같이 commit 해주세요. 
gradle/, gradlew, gradlew.bat 이렇게 세개 입니다.

2017-08-27 13:18 UTC, goinhacker approved these changes

2017-08-27 13:42 UTC, merged